Document: fastsms
Title: Debian fastsms Manual
Author: <insert document author here>
Abstract: This manual describes what fastsms is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/fastsms/fastsms.sgml.gz

Format: postscript
Files: /usr/share/doc/fastsms/fastsms.ps.gz

Format: text
Files: /usr/share/doc/fastsms/fastsms.text.gz

Format: HTML
Index: /usr/share/doc/fastsms/html/index.html
Files: /usr/share/doc/fastsms/html/*.html
